/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#ffdad6',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'secondary-fixed-dim': '#f9bd22',
        'on-primary-fixed': '#001f25',
        'primary-fixed': '#a2eeff',
        'on-primary': '#00363e',
        'on-tertiary': '#00354a',
        'surface': '#0b1326',
        'inverse-on-surface': '#283044',
        'tertiary-container': '#68cbff',
        'secondary-fixed': '#ffdf9f',
        'surface-container-lowest': '#060e20',
        'outline-variant': '#3c494c',
        'background': '#0b1326',
        'inverse-primary': '#006877',
        'primary-fixed-dim': '#2fd9f4',
        'secondary-container': '#e3aa00',
        'inverse-surface': '#dae2fd',
        'on-primary-container': '#005763',
        'on-secondary-fixed': '#261a00',
        'on-secondary': '#402d00',
        'on-secondary-container': '#5a4100',
        'secondary': '#ffc640',
        'tertiary': '#b6e2ff',
        'on-error': '#690005',
        'on-background': '#dae2fd',
        'surface-tint': '#2fd9f4',
        'error': '#ffb4ab',
        'surface-container': '#171f33',
        'on-tertiary-container': '#005574',
        'on-tertiary-fixed-variant': '#004c69',
        'surface-container-highest': '#2d3449',
        'tertiary-fixed-dim': '#7bd0ff',
        'error-container': '#93000a',
        'tertiary-fixed': '#c4e7ff',
        'on-tertiary-fixed': '#001e2c',
        'primary-container': '#22d3ee',
        'on-surface': '#dae2fd',
        'surface-container-high': '#222a3d',
        'surface-container-low': '#131b2e',
        'on-surface-variant': '#bbc9cd',
        'primary': '#8aebff',
        'on-primary-fixed-variant': '#004e5a',
        'outline': '#859397',
        'on-secondary-fixed-variant': '#5c4300',
        'surface-dim': '#0b1326',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
};
